print ("Hello apapi")
otaku = input('Fale o teu anime preferido nhyaa: ')
print(otaku,"?")
fujoshi= input('pessimo gosto, escolha outro: ' )
print(fujoshi,' né ? Realmente teu gosto é péssimo ' )
